bugtracker/models.py
from bugtracker.extensions import db


log_bug = db.Table('log_bug',
    db.Column('log_id', db.Integer, db.ForeignKey('log.id'), primary_key=True),
    db.Column('bug_id', db.Integer, db.ForeignKey('bug.id'), primary_key=True)
)

class Bug(db.Model):
    __tablename__ = 'bug'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True, nullable=False)
    description = db.Column(db.String(2500), nullable=False)
    
    @property
    def calories(self):
        return self.description

class Log(db.Model):
    __tablename__ = 'log'

    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.Date, nullable=False)
    bugs = db.relationship('Bug', secondary=log_bug)

bugtracker/__init__.py
from flask import Flask 
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

from .main.routes import main
from .extensions import db


def create_app():
    app = Flask(__name__)

    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite3'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    migrate = Migrate(app, db)

    db.init_app(app)
    app.register_blueprint(main)

    with app.app_context():
        db.create_all()

    return app

bugtracker/main/routes.py
from flask import Blueprint, render_template, request, redirect, url_for

from bugtracker.models import Bug, Log
from bugtracker.extensions import db

from datetime import datetime 

main = Blueprint('main', __name__)

@main.route('/')
def index():
    logs = Log.query.order_by(Log.date.desc()).all()

    log_dates = []

    for log in logs:
        description = ''

        for bug in log.bugs:
            description += str(bug.description)

        log_dates.append({
            'log_date' : log,
            'description' : description,
        })

    return render_template('index.html', log_dates=log_dates)

@main.route('/create_log', methods=['POST'])
def create_log():
    date = request.form.get('date')

    if not date:
        # Handle the case where date is empty (you can redirect or show an error message)
        return redirect(url_for('main.index'))

    log = Log(date=datetime.strptime(date, '%Y-%m-%d'))

    db.session.add(log)
    db.session.commit()

    return redirect(url_for('main.view', log_id=log.id))

@main.route('/add')
def add():
    bugs = Bug.query.all()

    return render_template('add.html', bugs=bugs, bug=None)

@main.route('/add', methods=['POST'])
def add_post():
    bug_name = request.form.get('bug-name')
    description = request.form.get('description')

    bug_id = request.form.get('bug-id')

    if bug_id:
        bug = Bug.query.get_or_404(bug_id)
        bug.name = bug_name
        bug.description= description

    else:
        new_bug = Bug(
            name=bug_name,
            description=description, 
        )
    
        db.session.add(new_bug)

    db.session.commit()

    return redirect(url_for('main.add'))

@main.route('/delete_bug/<int:bug_id>')
def delete_bug(bug_id):
    bug = Bug.query.get_or_404(bug_id)
    db.session.delete(bug)
    db.session.commit()

    return redirect(url_for('main.add'))

@main.route('/edit_bug/<int:bug_id>')
def edit_bug(bug_id):
    bug = Bug.query.get_or_404(bug_id)
    bugs = Bug.query.all()

    return render_template('add.html', bug=bug, bugs=bugs)
    
@main.route('/view/<int:log_id>')
def view(log_id):
    log = Log.query.get_or_404(log_id)

    bugs = Bug.query.all()

    totals = {
        'descr' : '',
    }

    for bug in log.bugs:
        totals['descr'] += str(bug.description)

    return render_template('view.html', bugs=bugs, log=log, totals=totals)

@main.route('/add_bug_to_log/<int:log_id>', methods=['POST'])
def add_bug_to_log(log_id):
    log = Log.query.get_or_404(log_id)

    selected_bug = request.form.get('bug-select')

    if selected_bug is not None:
        bug = Bug.query.get(int(selected_bug))

        log.bugs.append(bug)
        db.session.commit()

    return redirect(url_for('main.view', log_id=log_id))

@main.route('/remove_bug_from_log/<int:log_id>/<int:bug_id>')
def remove_bug_from_log(log_id, bug_id):
    log = Log.query.get(log_id)
    bug = Bug.query.get(bug_id)

    log.bugs.remove(bug)
    db.session.commit()

    return redirect(url_for('main.view', log_id=log_id))

bugtracker/templates/add.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Bug Tracker | Add Bug Report</title>

		<link href="https://fonts.googleapis.com/css?family=Oswald|Ubuntu:400,700" rel="stylesheet">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='bs/css/united.min.css') }}" />
		<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>

		<div class="container-fluid" id="wrapper">
			
			<div class="row" id="homeJumbo">
				<div class="overlay"></div>
				<div class="col-lg-12">
					<h1>
						<a href="{{ url_for('main.index') }}">BUG TRACKER</a>
					</h1>
					
					<div class="row t20">
						<div class="col-lg-4 col-lg-offset-4">
							<ul class="nav nav-pills nav-justified">
							  <li role="presentation">
							  	<a href="{{ url_for('main.index') }}" title="Home">Home</a>
							  </li>
							  <li role="presentation" class="active">
							  	<a href="{{ url_for('main.add') }}" title="Add Bug Report">Add Bug Report</a>
							  </li>
							</ul>
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-8 col-lg-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="lean-h text-black">
								<i class="glyphicon glyphicon-plus-sign"></i> New Bug Form
							</h3>
							<hr />

							<form action="{{ url_for('main.add') }}" method="POST" role="form">
							
								<div class="row">
									<div class="col-lg-4">
										<div class="form-group">
											<label for="bug-name">Bug Name</label>
						                  	<input type="text" class="form-control" id="bug-name" name="bug-name" placeholder="Bug Name" value="{{ bug.name }}" autofocus>
										</div>
									</div>
									<div class="col-lg-4">
										<div class="form-group">
						                  <label for="descr">Description</label>
						                  <input type="text" class="form-control" id="descr" name="description" placeholder="Description..." value="{{ bug.descritpion }}">
						                </div>
									</div>
								</div>
								<div class="row">
									<div class="col-lg-4">
										<div class="form-group">
											<label style="visibility:hidden">Submit</label>
											<input type="hidden" name="food-id" value="{{ bug.id }}" >
											<button type="submit" class="btn btn-primary btn-block">
												<i class="glyphicon glyphicon-upload"></i> Submit
											</button>
										</div>
									</div>
								</div>
							
							</form>	
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-8 col-lg-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h4 class="lean-h text-black">
								<i class="glyphicon glyphicon-th-list"></i> Existing Bug Reports
							</h4>
						</div>
						<div class="table-responsive">
							<table class="table table-striped table-hover table-bordered">
								<thead>
									<tr>
										<th style="width: 5%;">#</th>
										<th>Name</th>
										<th style="width: 80%;">Description</th>
									</tr>
								</thead>
								<tbody>
									{% for bug in bugs %}
									<tr>
										<td>{{ bug.id }}</td><td>{{ bug.name }}</td><td>{{ bug.description }}</td>
										<td>
											<a href="{{ url_for('main.edit_bug', bug_id=bug.id) }}" class="btn btn-default btn-xs">
												<i class="glyphicon glyphicon-pencil"></i> Edit
											</a> 
											<a href="{{ url_for('main.delete_bug', bug_id=bug.id) }}" class="btn btn-danger btn-xs">
												<i class="glyphicon glyphicon-trash"></i> Delete
											</a> 
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>

			<footer>
				<div class="row pad">
					<div class="col-lg-12 text-center">
						Copyright &copy; 2023 <strong>Bug Tracker</strong>
					</div>
				</div>
			</footer>

		</div>

		<!-- jQuery -->
		<script src="{{ url_for('static', filename='bs/js/jquery.min.js') }}"></script>
		<!-- Bootstrap JavaScript -->
		<script src="{{ url_for('static', filename='bs/js/bootstrap.min.js') }}"></script>
	</body>
</html>

bugtracker/templates/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Bug Tracker | Home</title>

		<link href="https://fonts.googleapis.com/css?family=Oswald|Ubuntu:400,700" rel="stylesheet">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='bs/css/united.min.css') }}" />
		<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>

		<div class="container-fluid" id="wrapper">
			
			<div class="row" id="homeJumbo">
				<div class="overlay"></div>
				<div class="col-lg-12">
					<h1>
						<a href="{{ url_for('main.index') }}">BUG TRACKER</a>
					</h1>
					
					<div class="row t20">
						<div class="col-lg-4 col-lg-offset-4">
							<ul class="nav nav-pills nav-justified">
							  <li role="presentation" class="active">
							  	<a href="{{ url_for('main.index') }}" title="Home">Home</a>
							  </li>
							  <li role="presentation">
							  	<a href="{{ url_for('main.add') }}" title="Add Bug Report">Add Bug Report</a>
							  </li>
							</ul>
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-4 col-lg-offset-4">
					<div class="panel panel-default">
						<div class="panel-body">
							<form action="{{ url_for('main.create_log') }}" method="POST" role="form">
							
								<div class="form-group">
									<label><i class="glyphicon glyphicon-plus-sign"></i> Add New Date</label>
									<div class="input-group">
									  <input type="date" class="form-control" name="date" placeholder="Select New Date" aria-label="date" aria-describedby="add-btn">
									  <span class="input-group-btn">
										<button type="submit" class="btn btn-primary" id="add-btn">
										  <i class="glyphicon glyphicon-plus-sign"></i> Add_Date
										</button>
									  </span>
									</div>
								</div>
							
							</form>	
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-12">
					<h4 class="text-center text-white"><strong>Existing Records ({{ log_dates|length }})</strong></h4>
				</div>
			</div>

			{% for row in log_dates|batch(4) %}
			<div class="row t20">
				{% for log_date in row %}
				<div class="col-lg-3">
					<div class="panel panel-warning">
						<div class="panel-body text-bold">
							<i class="glyphicon glyphicon-calendar"></i> {{ log_date['log_date'].date.strftime('%B %d, %Y') }}

							<a class="btn btn-primary btn-xs pull-right" href="{{ url_for('main.view', log_id=log_date['log_date'].id) }}">
								View <i class="glyphicon glyphicon-arrow-right"></i>
							</a>
						</div>
						<ul class="list-group">
							<li class="list-group-item text-bold"><span class="badge">{{ log_date['description'] }}</span> Description</li>
						</ul>
					</div>
				</div>
				{% endfor %}
			</div>
			{% endfor %}

			<footer>
				<div class="row pad">
					<div class="col-lg-12 text-center">
						Copyright &copy; 2023 <strong>Bug Tracker</strong>
					</div>
				</div>
			</footer>

		</div>

		<!-- jQuery -->
		<script src="{{ url_for('static', filename='bs/js/jquery.min.js') }}"></script>
		<!-- Bootstrap JavaScript -->
		<script src="{{ url_for('static', filename='bs/js/bootstrap.min.js') }}"></script>
	</body>
</html>

bugtracker/templates/view.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Bug Tracker | View Details</title>

		<link href="https://fonts.googleapis.com/css?family=Oswald|Ubuntu:400,700" rel="stylesheet">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='bs/css/united.min.css') }}" />
		<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>

		<div class="container-fluid" id="wrapper">
			
			<div class="row" id="homeJumbo">
				<div class="overlay"></div>
				<div class="col-lg-12">
					<h1>
						<a href="{{ url_for('main.index') }}">BUG TRACKER</a>
					</h1>
					
					<div class="row t20">
						<div class="col-lg-4 col-lg-offset-4">
							<ul class="nav nav-pills nav-justified">
							  <li role="presentation">
							  	<a href="{{ url_for('main.index') }}" title="Home">Home</a>
							  </li>
							  <li role="presentation">
							  	<a href="{{ url_for('main.add') }}" title="Add Bug Report">Add Bug Report</a>
							  </li>
							</ul>
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-4 col-lg-offset-4">
					<div class="panel panel-default">
						<div class="panel-body">
							<form action="{{ url_for('main.add_bug_to_log', log_id=log.id) }}" method="POST" role="form">
							
								<div class="form-group">
									<label>Add Bug</label>
									<div class="input-group">
									  <select class="form-control" name="bug-select">
										  {% for bug in bugs %}     
											<option value="{{ bug.id }}">{{ bug.name }}</option>
									      {% endfor %}
					                    </select>
									  <span class="input-group-btn">
										<button type="submit" class="btn btn-primary" id="add-btn">
										  <i class="glyphicon glyphicon-plus-sign"></i> Add Bug
										</button>
									  </span>
									</div>
								</div>
							
							</form>	
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-8 col-lg-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="lean-h text-black">
								<i class="glyphicon glyphicon-calendar"></i> {{ log.date.strftime('%B %d, %Y') }}
							</h3>

							<div class="row">
								<div class="col-lg-3">
									<h4 class="lean-h">
										Description: &nbsp;<strong class="f25">{{ totals['descr'] }}</strong>
									</h4>
								</div>
							</div>
						</div>
						<div class="table-responsive">
							<table class="table table-striped table-hover table-bordered">
								<thead>
									<tr>
										<th style="width: 5%;">#</th>
										<th>Name</th>
										<th style="width: 70%;">Description</th>
										<th style="width: 25%;">Actions</th>
									</tr>
								</thead>
								<tbody>
									{% for bug in log.bugs %}
									<tr>
										<td>{{ loop.index }}</td><td>{{ bug.name }}</td><td>{{ bug.description }}</td>
										<td>
											<a href="{{ url_for('main.remove_bug_from_log', log_id=log.id, bug_id=bug.id) }}" class="btn btn-danger btn-xs">
												<i class="glyphicon glyphicon-trash"></i> Delete
											</a> 
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>

			<footer>
				<div class="row pad">
					<div class="col-lg-12 text-center">
						Copyright &copy; 2023 <strong>Bug Tracker</strong>
					</div>
				</div>
			</footer>

		</div>

		<!-- jQuery -->
		<script src="{{ url_for('static', filename='bs/js/jquery.min.js') }}"></script>
		<!-- Bootstrap JavaScript -->
		<script src="{{ url_for('static', filename='bs/js/bootstrap.min.js') }}"></script>
	</body>
</html>